# Build settings
remote_theme: diezcami/polar-bear-theme

# Site settings
title: Polar Bear
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dwarf.pro/English" # the base hostname & protocol for your site
twitter_username: lonelydwarf
github_username: lonelydwarffiles

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
theme: jekyll-theme-hacker